print("Daily Routine")
print("1. Wake up at 6:00 AM")
print("2. get ready for the day (shower, brush teeth, etc.) from 6:00 AM to 6:30 AM")   
print("3. Eat a healthy breakfast from 6:30 AM to 7:00 AM")
print("4. Start study from 7:00 AM to 12:00 PM")
print("5. Take a lunch break from 12:00 PM to 1:00 PM")
print("6. Continue study from 1:00 PM to 5:00 PM")
print("6. Engage in hobbies or relaxation from 5:00 PM to 7:00 PM")
print("7. Eat a healthy dinner from 7:00 PM to 7:30 PM")
print("8. get ready for bed (brush teeth, wash face,..etc.) from 7:30 PM to 8:00 PM")
print("9. Go to bed at 8:00")
study_hours_per_day = (12 - 7) + (5 - 1)
print("Total study hours per day:", study_hours_per_day)
print("Total study hours per week:", study_hours_per_day * 7)
